export const mockUser = {
  id: '1',
  email: 'alex@example.com',
  full_name: 'Alex Johnson',
  avatar_url: null,
  phone: '+1 (555) 123-4567',
  address: '123 Financial Ave',
  city: 'San Francisco',
  country: 'USA',
};

export const mockAccounts = [
  {
    id: '1',
    user_id: '1',
    account_name: 'Checking Account',
    account_number: '****1234',
    account_type: 'checking',
    balance: 5420.50,
    currency: 'USD',
    is_primary: true,
  },
  {
    id: '2',
    user_id: '1',
    account_name: 'Savings Account',
    account_number: '****5678',
    account_type: 'savings',
    balance: 25000.00,
    currency: 'USD',
    is_primary: false,
  },
];

export const mockTransactions = [
  {
    id: '1',
    account_id: '1',
    transaction_type: 'purchase',
    amount: 45.99,
    currency: 'USD',
    description: 'Coffee at Brew Haven',
    recipient_name: 'Brew Haven',
    status: 'completed',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    account_id: '1',
    transaction_type: 'transfer',
    amount: 500.00,
    currency: 'USD',
    description: 'Transfer to Savings',
    recipient_name: 'Savings Account',
    status: 'completed',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    account_id: '1',
    transaction_type: 'purchase',
    amount: 120.00,
    currency: 'USD',
    description: 'Grocery Store',
    recipient_name: 'Fresh Market',
    status: 'completed',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    account_id: '1',
    transaction_type: 'deposit',
    amount: 3000.00,
    currency: 'USD',
    description: 'Salary Deposit',
    recipient_name: 'Direct Deposit',
    status: 'completed',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockCards = [
  {
    id: '1',
    user_id: '1',
    account_id: '1',
    card_type: 'debit',
    card_number: '•••• •••• •••• 1234',
    cardholder_name: 'ALEX JOHNSON',
    expiry_date: '12/26',
    is_active: true,
  },
  {
    id: '2',
    user_id: '1',
    account_id: '1',
    card_type: 'credit',
    card_number: '•••• •••• •••• 5678',
    cardholder_name: 'ALEX JOHNSON',
    expiry_date: '08/27',
    is_active: true,
  },
];

export const mockBills = [
  {
    id: '1',
    account_id: '1',
    biller_name: 'Electric Company',
    amount: 120.00,
    due_date: '2026-05-15',
    status: 'pending',
    category: 'utility',
  },
  {
    id: '2',
    account_id: '1',
    biller_name: 'Internet Provider',
    amount: 79.99,
    due_date: '2026-05-10',
    status: 'pending',
    category: 'utility',
  },
  {
    id: '3',
    account_id: '1',
    biller_name: 'Insurance Company',
    amount: 250.00,
    due_date: '2026-05-20',
    status: 'paid',
    category: 'insurance',
  },
];

export const mockBudgets = [
  {
    id: '1',
    user_id: '1',
    category: 'Food & Dining',
    budget_amount: 600.00,
    spent_amount: 480.50,
    period: 'monthly',
    start_date: '2026-04-01',
    end_date: '2026-04-30',
  },
  {
    id: '2',
    user_id: '1',
    category: 'Entertainment',
    budget_amount: 300.00,
    spent_amount: 125.00,
    period: 'monthly',
    start_date: '2026-04-01',
    end_date: '2026-04-30',
  },
  {
    id: '3',
    user_id: '1',
    category: 'Shopping',
    budget_amount: 400.00,
    spent_amount: 398.99,
    period: 'monthly',
    start_date: '2026-04-01',
    end_date: '2026-04-30',
  },
  {
    id: '4',
    user_id: '1',
    category: 'Transport',
    budget_amount: 250.00,
    spent_amount: 80.00,
    period: 'monthly',
    start_date: '2026-04-01',
    end_date: '2026-04-30',
  },
];
